name: salary_tracker
description: Track your salary, savings and spending with Firebase sync.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Biometrics + secure storage
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

  # UI / utils
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  provider: ^6.1.2

  # Export
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
