// File generated by the FlutterFire CLI — THIS IS A PLACEHOLDER.
//
// Run `flutterfire configure` in the project root (see README.md, step 2)
// to replace this file automatically with your real project's values.
// Until you do that, the app will NOT connect to Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This project is not configured for web. Run flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate them.',
        );
    }
  }

  // ⚠️ REPLACE THESE with the values from your own Firebase project.
  // `flutterfire configure` will overwrite this whole file for you —
  // these placeholders exist only so the project compiles before that step.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIvKcXMt2d8K1Jhtq-v-prKId8SLgGscY',
    appId: '1:870048504905:android:7643af1b6da4efd17d7398',
    messagingSenderId: '870048504905',
    projectId: 'payslip-3df25',
    storageBucket: 'payslip-3df25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'com.example.salaryTracker',
  );
}
